openapi: 3.0.1
info:
  title: Books API
  version: "0.1"
paths:
  /books/list:
    get:
      operationId: list
      responses:
        "200":
          description: list 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Book"
  /books/show:
    get:
      operationId: show
      responses:
        "200":
          description: show 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Book"
components:
  schemas:
    Book:
      required:
      - name
      type: object
      properties:
        name:
          minLength: 1
          type: string
        isbn:
          type: string
          nullable: true
        pages:
          minimum: 0
          exclusiveMinimum: true
          type: integer
          format: int32
          nullable: true
