name: Java CI with Gradle
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        module: [ 'bean-introspection', 'bean-mapping', 'at-builder', 'json-serialization-serde', 'http-client-netty-manual', 'http-client-netty-declarative', 'routing-controller-get',  'routing-controller-method-httprequest-param', 'routing-path-parameter', 'routing-controller-query-param', 'routing-controller-query-param-validation', 'configuration-immutable-configuration-properties', 'configuration-configuration-properties', 'routing-jaxrs-get', 'vnderror', 'problemjson']
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build ${{ matrix.module }}
        run: cd ${{ matrix.module }}; ./gradlew build
